/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "cubeta.starter.settings": [],
    "cubeta.starter.settings.set": [],
    "cubeta.starter.add.actor": [],
    "cubeta.starter.clear.logs": [],
    "cubeta.starter.generate.page": [],
    "cubeta.starter.generate": [],
    "set-locale": [],
    "v1.web.public.index": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
